export const FETCHING_MOVIES = "FETCHING_MOVIES";
export const FETCHING_NEXT_PAGE_MOVIES = "FETCHING_NEXT_PAGE_MOVIES";
export const RECEIVED_DATA = "RECEIVED_DATA";
export const ERROR_GETTING_MOVIES = "ERROR_GETTING_MOVIES";